version: "3.8"
services:
  frontend:
    build: ./client
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - ./client/.env

  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped
    environment:
      - NODE_ENV=production
